version: 2
updates:
  - package-ecosystem: npm
    schedule:
      interval: monthly
    directories:
      - .
    groups:
      all:
        applies-to: version-updates
        patterns:
          - "*"
      all_security:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: github-actions
    schedule:
      interval: monthly
    directories:
      - .
    groups:
      all:
        applies-to: version-updates
        patterns:
          - "*"
      all_security:
        applies-to: security-updates
        patterns:
          - "*"
      